config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  get 'pages/home'
  root "pins#index"
  get "about" => "pages#about"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	validates :description, presence: true
	validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new]

  respond_to :html

  def index
    @pins = Pin.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.build
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    @pin.save
    respond_with(@pin)
  end

  def update

    @pin.update(pin_params)
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "No puedes editar este pin porque no es tuyo" if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_flash.html.erb
<% if notice || alert %>
  <div class="flash-message <%= notice ? "notice" : ""%><%= alert ? "error" : ""%>">
    <div class="container container_12 clearfix">
      <div class="grid_12">
        <% if notice %>
          <p><%= notice %></p>
        <% elsif alert %>
          <p><%= alert %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pins ", root_path , class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
              <strong class="newPin">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> New Pin
              </strong>
            <% end %>
          </li>


        <% end %>
        <li><%= link_to "Inicio",  root_path %></li>
        <li><%= link_to "Nosotros",  about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Configuración de la cuenta", edit_user_registration_path %></li>
          <li><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %></li>
        <% else %>  
          <li><%= link_to "Iniciar sesion",  new_user_session_path%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>

	<div class="container-fluid" align="center">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron">
	<h1>Pins</h1>

	<% if user_signed_in? %>
		<%= link_to "Ver pins", pins_path, class:"btn btn-primary btn-lg"%>
	<% else %>
		<%= link_to "Registrate", new_user_registration_path, class:"btn btn-primary btn-lg"%>
		<%= link_to "Inicia Sesion", new_user_session_path, class:"btn btn-primary btn-lg"%>
	<% end %>
	
</div>

app/views/pages/about.html.erb
<div class="jumbotron">
	<h1>ExtraNet Openbravo</h1>
	<p>Consulta tu saldo, estado de cuenta y descarga tus CFDi's desde este sitio</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>ExtraNet</h1>

	<% if user_signed_in? %>
		<%= link_to "Ver pins", pins_path, class:"btn btn-primary btn-lg"%>
	<% else %>
		<%= link_to "Registrate", new_user_registration_path, class:"btn btn-primary btn-lg"%>
		<%= link_to "Inicia Sesion", new_user_session_path, class:"btn btn-primary btn-lg"%>
	<% end %>
	
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div  class="panel panel-default">
	
	<div  class="panel panel-heading">
      <h1>Editing pin</h1>
  	</div>

	<div  class="panel panel-body center-block">

		<%= render 'form' %> <br>

		<%= link_to 'Show', @pin, class: "btn btn-primary"  %>
		<%= link_to 'Back', pins_path, class: "btn btn-primary"  %>

	</div>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' if !user_signed_in?%>
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
        <div class="box panel panel-default">
          <%= link_to (image_tag pin.image.url(:medium)), pin%>
          <br>
          <div class="panel-body">
          
            <%= pin.description %>
            <br>
            <strong><%= pin.user.name if pin.user %></strong>
            
            <% if current_user == pin.user %>
              <div class="actions">
                  <%= link_to edit_pin_path(pin), class: "btn btn-primary" do %>
                    <span class="glyphicon glyphicon-edit" aria-hidden="false"></span> Editar
                  <% end %>
                  <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" do %>
                    <span class="glyphicon glyphicon-trash" aria-hidden="false"></span> Borrar
                  <% end %>
              </div>
            <% end %>

          </div>
        </div>
  <% end %>
</div>
 <%= will_paginate @posts, renderer: BootstrapPagination::Rails%> 

app/views/pins/new.html.erb
<div  class="panel panel-default">
	<div  class="panel panel-heading">
      <h1>New pin</h1>
  	</div>

	<div  class="panel panel-body center-block">
		<%= render 'form' %>
		<br>
		<%= link_to 'Back', pins_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/pins/show.html.erb
<div  class="panel panel-default">
	<p id="notice"><%= notice %></p>

	<div  class="panel-body">
		<p>
		    <%= link_to pins_path, class: "btn btn-primary" do %>
	                <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="false"></span> Atrás
            <% end %>

		    <%if @pin.user == current_user %>
		      	<%= link_to edit_pin_path(@pin), class: "btn btn-primary" do %>
	                <span class="glyphicon glyphicon-edit" aria-hidden="false"></span> Editar
            	<% end %>
			<% end %>

		    <br><br>
		    <strong><%= @pin.user.name %></strong>
		    <br>
			<strong><%= @pin.description %></strong>		 	
		  	<br><br>

		  	<%= image_tag @pin.image.url%>
		</p>

		
	</div>
</div>